# Generated by Django 3.2.16 on 2023-03-16 20:17

from django.db import migrations, models
import django.db.models.deletion
import food_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_auto_20230317_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=food_app.models.get_uploading_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscribe',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribes', to='food_app.subscription', verbose_name='Подписка'),
        ),
    ]
