# Generated by Django 3.2.16 on 2023-03-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_customer_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscribe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribes', to='food_app.subscription', verbose_name='Подписка'),
        ),
    ]
