# Generated by Django 3.2.16 on 2023-03-17 02:02

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_alter_customer_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_method',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Способ приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание'),
        ),
    ]
