# Generated by Django 3.2.16 on 2023-03-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0007_recipeingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
    ]
