# Generated by Django 3.2.16 on 2023-03-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_auto_20230317_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='weight',
        ),
    ]
