# Generated by Django 3.2.16 on 2023-03-17 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_app', '0009_remove_ingredient_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='food_app.customer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='allergies',
        ),
        migrations.AddField(
            model_name='plan',
            name='allergies',
            field=models.ManyToManyField(related_name='plans', to='food_app.AllergicCategory', verbose_name='Аллергии'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan', to='food_app.planperiod', verbose_name='Срок подписки'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
