# Generated by Django 3.2.16 on 2023-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0011_plan_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end',
            field=models.DateTimeField(verbose_name='Окончание подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало подписки'),
        ),
    ]
