# Generated by Django 3.2.16 on 2023-03-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0012_auto_20230317_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
    ]
