# Generated by Django 3.2.16 on 2023-03-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0014_auto_20230317_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='calories',
        ),
    ]
