# Generated by Django 3.2.16 on 2023-03-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0016_auto_20230318_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('gram', 'гр.'), ('item', 'шт.'), ('slice', 'дол.'), ('spoon_small', 'ч.л.'), ('spoon', 'ст.л.'), ('volume', 'мл.'), ('pitch', 'щеп.')], default=1, max_length=20, verbose_name='Единицы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость блюда'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['calories'], name='food_app_re_calorie_32a54a_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['price'], name='food_app_re_price_4192b7_idx'),
        ),
    ]
