# Generated by Django 3.2.16 on 2023-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0016_auto_20230318_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='allergies',
            field=models.ManyToManyField(
                blank=True,
                related_name='plans',
                to='food_app.AllergicCategory',
                verbose_name='Аллергии',
            ),
        ),
        migrations.RemoveField(
            model_name='plan',
            name='food_intakes',
        ),
        migrations.AddField(
            model_name='plan',
            name='food_intakes',
            field=models.ManyToManyField(
                related_name='plans', to='food_app.FoodIntake', verbose_name='Приемы пищи'
            ),
        ),
    ]
