# Generated by Django 3.2.16 on 2023-03-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0017_auto_20230318_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintake',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=100, max_digits=8, verbose_name='Стоимость категории'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(
                choices=[
                    ('gram', 'гр.'),
                    ('item', 'шт.'),
                    ('slice', 'дол.'),
                    ('spoon_small', 'ч.л.'),
                    ('spoon', 'ст.л.'),
                    ('volume', 'мл.'),
                    ('pitch', 'щеп.'),
                ],
                default=1,
                max_length=20,
                verbose_name='Единицы',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planperiod',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=100, max_digits=8, verbose_name='Стоимость периода'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name='Стоимость блюда',
            ),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='food_app.plan', verbose_name='План'
            ),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['calories'], name='food_app_re_calorie_32a54a_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['price'], name='food_app_re_price_4192b7_idx'),
        ),
    ]
