# Generated by Django 3.2.16 on 2023-03-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0018_auto_20230318_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(verbose_name='Начало действия промокода')),
                ('end_at', models.DateField(verbose_name='Конец действия промокода')),
                ('discount', models.SmallIntegerField(verbose_name='Размер скидки')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='food_app.promocode', verbose_name='Промокод'),
        ),
    ]
