# Generated by Django 3.2.16 on 2023-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0019_auto_20230319_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AddField(
            model_name='promocode',
            name='promocode',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['start_at'], name='food_app_pr_start_a_055f81_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['end_at'], name='food_app_pr_end_at_da8061_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['discount'], name='food_app_pr_discoun_53e57c_idx'),
        ),
    ]
