# Generated by Django 3.2.16 on 2023-03-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0020_auto_20230319_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergic_categories',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='food_app.AllergicCategory', verbose_name='Категории аллергенов'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='food_app.recipe', verbose_name='Рецепт')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='food_app.subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
