# Generated by Django 3.2.16 on 2023-03-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0021_auto_20230319_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodintake',
            name='price',
        ),
    ]
