# Generated by Django 3.2.16 on 2023-03-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0022_remove_foodintake_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
